Time::DATE_FORMATS[:short] = "%a %b %d"
Time::DATE_FORMATS[:date] = "%a %b %d, %Y"
Time::DATE_FORMATS[:time] = "%I:%M%p"
Time::DATE_FORMATS[:datetime] = "%a %b %d, %Y, %I:%M%p"
Time::DATE_FORMATS[:time_short] = "%l:%M%P"